# Generated by Django 4.0 on 2021-12-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='name',
        ),
    ]
